language: cpp
compiler: clang

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew-dev libjpeg8-dev libgpgme11-dev libsndfile1-dev libopenal-dev libudev-dev libjpeg62
  - wget -O SFML.tar.gz https://github.com/LaurentGomila/SFML/archive/2.2.tar.gz
  - tar -xzf SFML.tar.gz
  - cd SFML-2.2
  - cmake .
  - make && sudo make install
  - cd ..

script: cmake . && make
